# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

gems:
    [jekyll-paginate]

# Setup
title:               Holden-s的博客
description:         '思考、记录、分享'
url:                 http://holden-s.github.io
baseurl:             '/home'
paginate:            5

# About/contact
author:
  name:              holden-s
  url:               
  email:             

# Custom vars
version:             1.0.0
