# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

gems:
    [jekyll-paginate]

# Setup
title:               Holden-s的博客
tagline:             思考、总结、分享
description:         '本博客主题<a href="https://github.com/poole/lanyon" target="_blank">lanyon</a>由<a href="https://twitter.com/mdo" target="_blank">@mdo</a>维护'
url:                 http://holden-s.github.io
baseurl:             '/home'
paginate:            5

# About/contact
author:
  name:              holden-s
  url:               
  email:             

# Custom vars
version:             1.0.0
